/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: example.i

package exampleStruct

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_exampleStruct_e8c9c9002849162a(swig_intgo arg1);
extern void _wrap_S1_a_set_exampleStruct_e8c9c9002849162a(uintptr_t arg1, char arg2);
extern char _wrap_S1_a_get_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern void _wrap_S1_b_set_exampleStruct_e8c9c9002849162a(uintptr_t arg1, short arg2);
extern short _wrap_S1_b_get_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern void _wrap_S1_c_set_exampleStruct_e8c9c9002849162a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_S1_c_get_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern uintptr_t _wrap_new_S1_exampleStruct_e8c9c9002849162a(void);
extern void _wrap_delete_S1_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern void _wrap_S11_len_set_exampleStruct_e8c9c9002849162a(uintptr_t arg1, char arg2);
extern char _wrap_S11_len_get_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern void _wrap_S11_s1_set_exampleStruct_e8c9c9002849162a(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_S11_s1_get_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern uintptr_t _wrap_new_S11_exampleStruct_e8c9c9002849162a(void);
extern void _wrap_delete_S11_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
extern swig_intgo _wrap_SetS11_exampleStruct_e8c9c9002849162a(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_exampleStruct_e8c9c9002849162a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrS1 uintptr

func (p SwigcptrS1) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrS1) SwigIsS1() {
}

func (arg1 SwigcptrS1) SetA(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_S1_a_set_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrS1) GetA() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_S1_a_get_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrS1) SetB(arg2 uint16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_S1_b_set_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))
}

func (arg1 SwigcptrS1) GetB() (_swig_ret uint16) {
	var swig_r uint16
	_swig_i_0 := arg1
	swig_r = (uint16)(C._wrap_S1_b_get_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrS1) SetC(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_S1_c_set_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrS1) GetC() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_S1_c_get_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewS1() (_swig_ret S1) {
	var swig_r S1
	swig_r = (S1)(SwigcptrS1(C._wrap_new_S1_exampleStruct_e8c9c9002849162a()))
	return swig_r
}

func DeleteS1(arg1 S1) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_S1_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0))
}

type S1 interface {
	Swigcptr() uintptr
	SwigIsS1()
	SetA(arg2 byte)
	GetA() (_swig_ret byte)
	SetB(arg2 uint16)
	GetB() (_swig_ret uint16)
	SetC(arg2 uint)
	GetC() (_swig_ret uint)
}

type SwigcptrS11 uintptr

func (p SwigcptrS11) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrS11) SwigIsS11() {
}

func (arg1 SwigcptrS11) SetLen(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_S11_len_set_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrS11) GetLen() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_S11_len_get_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrS11) SetS1(arg2 S1) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_S11_s1_set_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrS11) GetS1() (_swig_ret S1) {
	var swig_r S1
	_swig_i_0 := arg1
	swig_r = (S1)(SwigcptrS1(C._wrap_S11_s1_get_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewS11() (_swig_ret S11) {
	var swig_r S11
	swig_r = (S11)(SwigcptrS11(C._wrap_new_S11_exampleStruct_e8c9c9002849162a()))
	return swig_r
}

func DeleteS11(arg1 S11) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_S11_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0))
}

type S11 interface {
	Swigcptr() uintptr
	SwigIsS11()
	SetLen(arg2 byte)
	GetLen() (_swig_ret byte)
	SetS1(arg2 S1)
	GetS1() (_swig_ret S1)
}

func SetS11(arg1 S11) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_SetS11_exampleStruct_e8c9c9002849162a(C.uintptr_t(_swig_i_0)))
	return swig_r
}
